# Generated by Django 5.1.2 on 2024-10-28 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=10)),
                ('data_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=20)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('series_title_1', models.CharField(max_length=100)),
                ('series_title_2', models.CharField(max_length=100)),
                ('series_title_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
