# Generated by Django 5.1.2 on 2024-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeindex',
            name='data_value',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradeindex',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tradeindex',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
